### ISSUE TITLE
Not working in python3 

### ISSUE THREAD

**Issue by mohitmaharana** [ewenchou/bluetooth-proximity#9] opened 2018-06-14 20:42 UTC
Traceback (most recent call last):
  File "lnsm.py", line 1, in <module>
    from bt_proximity import BluetoothRSSI
  File "/usr/local/lib/python3.5/dist-packages/bt_proximity-0.1-py3.5.egg/bt_proximity/__init__.py", line 1, in <module>
    from bt_rssi import BluetoothRSSI
ImportError: No module named 'bt_rssi'

**Comment by xiaoyu830411** [comment] 2018-09-19 09:27
I have same issue.

**Comment by ewenchou** [comment] 2018-12-08 19:11
Looks like duplicate of Issue #7

**Closed by ewenchou** 2018-12-08 19:11 UTC
